# Generated by Django 5.2 on 2026-07-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
