# Generated by Django 5.2 on 2026-09-17 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_sale_type_saleitem_label_alter_saleitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type_depense', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.company')),
            ],
            options={
                'db_table': 'depenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
