# Generated by Django 5.2 on 2026-09-18 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('PRODUCT', 'Produits'), ('SERVICE', 'Services'), ('MIXED', 'Mixte (produits + services)')], default='PRODUCT', max_length=10),
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnements', to='core.product')),
            ],
            options={
                'db_table': 'approvisionnements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
