# Generated by Django 5.2 on 2026-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sale_sale_type_approvisionnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SELLER', 'Gérant')], default='SELLER', max_length=10),
        ),
    ]
